version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: demetra_postgres
    environment:
      POSTGRES_USER: demetra_user
      POSTGRES_PASSWORD: demetra_pass
      POSTGRES_DB: demetra_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend_network

  redis:
    image: redis:latest
    container_name: demetra_redis
    ports:
      - "6379:6379"
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge
    external: true

volumes:
  postgres_data:
